//  @ts-check

import { tanstackConfig } from '@tanstack/eslint-config'

export default [
  ...tanstackConfig,
  {
    rules: {
      'import/no-cycle': 'off',
      'import/order': 'off',
      'sort-imports': 'off',
      '@typescript-eslint/array-type': 'off',
      '@typescript-eslint/require-await': 'off',
      'pnpm/json-enforce-catalog': 'off',
    },
  },
  {
    // Design system guard: components must take color from the semantic theme
    // tokens in src/styles.css (e.g. bg-primary, text-muted-foreground,
    // bg-income-bg), never raw color literals. `var(--…)` is allowed since it
    // points at a token. See CLAUDE.md › Design system / docs/adr/0005.
    files: ['src/**/*.{ts,tsx}'],
    ignores: ['src/lib/database.types.ts'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector:
            'Literal[value=/#([0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})\\b/]',
          message:
            'Use a semantic theme token (see CLAUDE.md › Design system), not a raw hex color.',
        },
        {
          selector: 'Literal[value=/\\brgba?\\(/]',
          message:
            'Use a semantic theme token (see CLAUDE.md › Design system), not a raw rgb()/rgba() color.',
        },
        {
          selector:
            'TemplateElement[value.raw=/#([0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})\\b/]',
          message:
            'Use a semantic theme token (see CLAUDE.md › Design system), not a raw hex color.',
        },
        {
          selector: 'TemplateElement[value.raw=/\\brgba?\\(/]',
          message:
            'Use a semantic theme token (see CLAUDE.md › Design system), not a raw rgb()/rgba() color.',
        },
      ],
    },
  },
  {
    ignores: [
      'eslint.config.js',
      'prettier.config.js',
      // Generated by `supabase gen types`; not hand-edited.
      'src/lib/database.types.ts',
    ],
  },
]
